version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: hints-tutor-bot:dev
    ports:
      - "8000:8000"
    environment:
      APP_ENV: development
      POSTGRES_URL: postgresql://postgres:postgres@postgres:5432/hints
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: hints
      MINIO_SECRET_KEY: hintssecret
    depends_on:
      - postgres
      - minio

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hints
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: hints
      MINIO_ROOT_PASSWORD: hintssecret
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:

